# Generated by Django 5.1.4 on 2025-01-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "name",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("instructions", models.TextField()),
                ("image_url", models.URLField()),
                ("preparation_time", models.PositiveSmallIntegerField(default=10)),
                ("cooking_time", models.PositiveSmallIntegerField(default=20)),
                ("number_of_servings", models.PositiveSmallIntegerField(default=4)),
                (
                    "description",
                    models.TextField(
                        default="This is a default description to the Recipe. Since TheMealDB API doesn't specify a lot of details to the recipes (description, cooking time, preparation time and number of servings), this one was made until it will be fixed manually later."
                    ),
                ),
                ("last_modified", models.DateField(auto_now=True)),
                ("has_been_updated", models.BooleanField(default=False)),
                ("tags", models.ManyToManyField(to="tag.tag")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=75)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipe.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipe.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipe.RecipeIngredient", to="recipe.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tools",
            field=models.ManyToManyField(to="recipe.tool"),
        ),
    ]
